#!/usr/bin/env node

'use strict';

const pkgJSON = require('../package.json');
const shouldRun = Boolean(pkgJSON['_where']);

if (!shouldRun) return;

const fork = require('child_process').fork;
const path = require('path');

const gulpBin = path.join(findNearestNodeModules('gulp'), '.bin', 'gulp');

fork(gulpBin, ['release']);

function findNearestNodeModules(moduleId) {
	let error;
	let modulePath;

	try {
		modulePath = require.resolve(moduleId);
	} catch (e) {
		error = e;
	}

	if (error) return console.error(error);

	let dir;
	let parentDir = path.dirname(modulePath);

	do {
		dir = parentDir;
		parentDir = path.resolve(dir, '..');
	} while (path.relative(parentDir, dir) !== 'node_modules' && parentDir !== '/');

	return dir;
}
