#!/usr/bin/env node

const spawn = require('child_process').spawn;

const pkgJSON = require('../package.json');

if (pkgJSON['_where']) {
	spawn('rm', [
		'-rf',
		'../packages',
		'../gulpfile.js',
		'../.*rc',
		'../*ignore',
		'../.*config',
		'../*.yml',
		'./scripts'
	], {cwd: __dirname});
}
