#!/usr/bin/env node

'use strict';

const pkgJSON = require('../package.json');
const shouldRun = Boolean(pkgJSON['_where']);

if (!shouldRun) return;

const spawn = require('child_process').spawn;

spawn('rm', [
	'-rf',
	'../packages',
	'../gulpfile.js',
	'../.babelrc',
	'../.gitignore',
	'../.editorconfig',
	'../.travis.yml'
], {cwd: __dirname});
